PATH : "/home/ninon/Documents/workflows_comparison_analysis/snakemake/"
REF : "../data/hg19.fasta"
ANNOTATION : "../data/ref-transcripts.gtf"
THREADS : 4
#CONTAINER : "docker://ninondm/workflow_comparison_analysis"
CONTAINER_FASTQC : "docker://biocontainers/fastqc:v0.11.9_cv7"
CONTAINER_FASTP : "docker://biocontainers/fastp:v0.20.1_cv1"
CONTAINER_HISAT2 : "docker://biocontainers/hisat2:v2.1.0-2-deb_cv1"
CONTAINER_SAMTOOLS : "docker://biocontainers/samtools:v1.7.0_cv4"
CONTAINER_CUFFLINKS : "docker://pgcbioinfo/cufflinks:2.2.1"