import os
import snakemake.io
import glob


configfile: "config.yaml"

(SAMPLES,READS,) = glob_wildcards("../data/{sample}_{read}.fq")
READS = ["1","2"]

rule all:
    input: 
        expand("results/{sample}_1_fastqc.zip",sample=SAMPLES),
        expand("results/{sample}_2_fastqc.zip",sample=SAMPLES), 
        expand("results/{sample}/transcripts.gtf",sample=SAMPLES),
        
include: "./rules/fastq.smk"  
include: "./rules/fastp.smk"
#include: "./rules/sortmerna.smk"
include: "./rules/hisat2.smk"
include: "./rules/samtools.smk"
include: "./rules/cufflinks.smk"

#expand("results/{sample}.sorted.bam",sample=SAMPLES),
#expand("results/{sample}.sam",sample=SAMPLES)
#expand("results/{sample}.{number}.ht2",sample=SAMPLES)
#expand("results/{sample}_other_sortmerna.fastq",sample=SAMPLES)
#expand("results/{sample}_aligned_sortmerna.fastq",sample=SAMPLES)
#expand("results/{sample}_1_trimmed.fastq.gz",sample=SAMPLES),
#expand("results/{sample}_2_trimmed.fastq.gz",sample=SAMPLES)
